### ISSUE TITLE
💎 sOMe cOMmANDs For CONveRtInG FiLEs ThrOugH tHe bOt 💎

### ISSUE THREAD

**Issue by D35P4C1T0** [Andry01k/PepeBOT#1]
!toGIF (videofiles as input, less than X seconds long)
!toPNG (other image files)
!toRAR (idk, anything)
!toZIP (goto RAR)
!toPDF (should accept docx and other office shit)
!toDOCX (same as PDF, but with ODT)
!toTXT (from CSVs, JSONs, raw BINs (?)) 
!toCSV (from TXTs)
!toJSON (TXTs and CSVs)

The command should read the extension of the input file and tell the user the available file formats. Files to be converted need to be sent to the bot by private chat. I'm open to suggestions.

**Comment by Andry01k** [comment]
not at the moment
